#!/usr/bin/env python3
"""
GitHub PR Integration for AI-ARB Recommendation System

This script formats recommendation crew output for GitHub PR comments,
enabling async SME collaboration without meetings.
"""

import os
import json
from pathlib import Path
from typing import Dict, List, Optional
from dataclasses import dataclass
from datetime import datetime

@dataclass
class PRCommentFormatter:
    """Formats recommendation output for GitHub PR comments"""

    max_comment_length: int = 65536  # GitHub's limit

    def format_for_pr_comment(self, recommendations: str, review_title: str) -> Dict[str, str]:
        """
        Format recommendations for GitHub PR comment with collapsible sections
        """
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M UTC")

        # Split recommendations into sections for better readability
        sections = self._parse_recommendations_sections(recommendations)

        comment_parts = [
            f"## 🤖 AI-ARB Architecture Review: {review_title}",
            f"**Generated:** {timestamp}",
            "",
            "### 📋 Executive Summary",
            self._extract_executive_summary(recommendations),
            "",
            "<details>",
            "<summary>🔍 Detailed Recommendations</summary>",
            "",
            self._format_detailed_sections(sections),
            "</details>",
            "",
            "### 💡 Next Steps",
            "- **Reviewers**: Please review recommendations above and provide feedback",
            "- **Implementation**: Address Phase 0 items immediately for risk mitigation",
            "- **Timeline**: Follow the phased roadmap for systematic improvements",
            "",
            "---",
            "*Generated by AI-ARB - Automated Architecture Review & Recommendations*"
        ]

        full_comment = "\n".join(comment_parts)

        # Handle GitHub comment length limits
        if len(full_comment) > self.max_comment_length:
            return self._split_into_multiple_comments(full_comment, review_title, timestamp)

        return {"comment": full_comment}

    def _parse_recommendations_sections(self, recommendations: str) -> Dict[str, str]:
        """Parse recommendations into logical sections"""
        sections = {}

        # Split by phase headers
        lines = recommendations.split('\n')
        current_section = "overview"
        current_content = []

        for line in lines:
            if line.startswith("PHASE ") and "IMMEDIATE" in line:
                sections[current_section] = '\n'.join(current_content)
                current_section = "phase_0_immediate"
                current_content = [line]
            elif line.startswith("PHASE ") and "TACTICAL" in line:
                sections[current_section] = '\n'.join(current_content)
                current_section = "phase_1_tactical"
                current_content = [line]
            elif line.startswith("PHASE ") and "STRATEGIC" in line:
                sections[current_section] = '\n'.join(current_content)
                current_section = "phase_2_strategic"
                current_content = [line]
            elif line.startswith("ACTION ITEMS:"):
                sections[current_section] = '\n'.join(current_content)
                current_section = "action_items"
                current_content = [line]
            elif line.startswith("TOTAL EFFORT ESTIMATE:"):
                sections[current_section] = '\n'.join(current_content)
                current_section = "effort_estimate"
                current_content = [line]
            else:
                current_content.append(line)

        sections[current_section] = '\n'.join(current_content)
        return sections

    def _extract_executive_summary(self, recommendations: str) -> str:
        """Extract or generate executive summary"""
        lines = recommendations.split('\n')

        # Look for explicit summary or generate from key points
        summary_lines = []
        for line in lines[:20]:  # Check first 20 lines
            if any(keyword in line.lower() for keyword in [
                'comprehensive', 'roadmap', 'provides', 'structured',
                'staged', 'path', 'mitigate', 'enhance', 'achieve'
            ]):
                summary_lines.append(line.strip())

        if summary_lines:
            return '\n'.join(summary_lines[:3])  # Limit to 3 lines

        # Fallback summary
        return ("This comprehensive architectural improvement roadmap provides a structured "
                "and staged path to enhance system reliability, security, scalability, and cost efficiency.")

    def _format_detailed_sections(self, sections: Dict[str, str]) -> str:
        """Format sections with collapsible subsections"""
        formatted = []

        section_headers = {
            "phase_0_immediate": "### 🚨 Phase 0: Immediate Risk Mitigation",
            "phase_1_tactical": "### 🔧 Phase 1: Tactical Improvements",
            "phase_2_strategic": "### 🎯 Phase 2: Strategic Enhancements",
            "action_items": "### 📝 Action Items & Timeline",
            "effort_estimate": "### ⏱️ Effort Estimate"
        }

        for section_key, header in section_headers.items():
            if section_key in sections and sections[section_key].strip():
                formatted.extend([
                    f"<details>",
                    f"<summary>{header.split(':')[1]}</summary>",
                    "",
                    "```markdown",
                    sections[section_key].strip(),
                    "```",
                    "",
                    "</details>",
                    ""
                ])

        return "\n".join(formatted)

    def _split_into_multiple_comments(self, full_comment: str, title: str, timestamp: str) -> Dict[str, str]:
        """Split long content into multiple GitHub comments"""
        comments = {}

        # Split by sections, keeping related content together
        parts = full_comment.split("### ")

        # First comment: Header + Executive Summary
        comments["comment_1"] = "\n".join([
            f"## 🤖 AI-ARB Architecture Review: {title} (Part 1/2)",
            f"**Generated:** {timestamp}",
            "",
            "### 📋 Executive Summary",
            self._extract_executive_summary(full_comment),
            "",
            "---",
            "*Part 1 of 2 - See comments below for detailed recommendations*"
        ])

        # Second comment: Detailed recommendations
        detailed_parts = [part for part in parts if part.startswith(("🚨", "🔧", "🎯", "📝", "⏱️"))]
        comments["comment_2"] = "\n".join([
            f"## 🤖 AI-ARB Architecture Review: {title} (Part 2/2)",
            "",
            "### " + "\n### ".join(detailed_parts),
            "",
            "### 💡 Next Steps",
            "- **Reviewers**: Please review recommendations above and provide feedback",
            "- **Implementation**: Address Phase 0 items immediately for risk mitigation",
            "",
            "---",
            "*Generated by AI-ARB - Automated Architecture Review & Recommendations*"
        ])

        return comments

def create_pr_comment_file(recommendations: str, review_title: str, output_dir: str = "pr_comments") -> str:
    """
    Create a formatted PR comment file from recommendations

    Args:
        recommendations: Raw recommendation output from crew
        review_title: Title of the architecture review
        output_dir: Directory to save PR comment files

    Returns:
        Path to the created PR comment file
    """
    formatter = PRCommentFormatter()

    # Create output directory
    output_path = Path(output_dir)
    output_path.mkdir(exist_ok=True)

    # Format for PR comment
    pr_comments = formatter.format_for_pr_comment(recommendations, review_title)

    # Create filename with timestamp
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    filename = f"pr_comment_{timestamp}.md"
    filepath = output_path / filename

    # Write the comment(s)
    with open(filepath, 'w', encoding='utf-8') as f:
        if "comment" in pr_comments:
            f.write(pr_comments["comment"])
        else:
            # Multiple comments
            for i, (key, content) in enumerate(pr_comments.items(), 1):
                f.write(f"## Comment {i}\n\n")
                f.write(content)
                f.write("\n\n---\n\n")

    print(f"✅ PR comment file created: {filepath}")
    return str(filepath)

if __name__ == "__main__":
    # Example usage
    sample_recommendations = """
PHASE 0 IMMEDIATE (Critical Risk Mitigation):
- Implement secrets management and remove hardcoded credentials
- Enforce HTTPS on all endpoints
- Configure API rate limiting

PHASE 1 TACTICAL (Core Infrastructure Improvements):
- Enable TLS encryption for internal services
- Implement robust authentication and authorization
- Set up monitoring and alerting

ACTION ITEMS:
| Action Item | Owner | Effort | Timeline | Success Criteria |
|-------------|-------|--------|----------|------------------|
| Implement secrets management | DevOps/Security | Medium | Weeks 1-2 | No credentials in code |

TOTAL EFFORT ESTIMATE:
- Duration: 5-6 months
- Team Size: Cross-functional teams
"""

    comment_file = create_pr_comment_file(
        sample_recommendations,
        "AI-Powered Supply Chain Architecture Review"
    )

    print(f"PR comment file ready for copy-paste to GitHub: {comment_file}")